#!/bin/bash
set -o pipefail

# Lists all connected outputs
get_outputs() {
    xrandr | grep "[^s]connected" | \
        awk "{ print \" \" \$1 \"\\0icon\\x1fdesktopconnected\" }"
    xrandr | grep "disconnected" | \
        awk "{ print \" \" \$1 \"\\0icon\\x1fdesktopdisconnected\"}"
}

# Lists all modes for given output
get_modes() {
    res=$(xrandr | sed "1,/^$1\s/d" | sed "/^\w/Q")

    if [[ -z "$res" ]]; then 
        echo "No such X output" >&2
        exit 1
    else 
        echo "$res"
    fi
}

# Lists all resolutions for given output (and option to turn off)
get_resolutions() {
    get_modes "$1" | awk "{ print \$1 }" || exit 1
}

parse_indicators() {
    indicators=""
    if [[ $1 == *"*"* ]]; then
        indicators="current"
    fi

    if [[ $1 == *"+"* ]]; then
        if [[ -n "$indicators" ]]; then
            indicators="${indicators}, "
        fi
        indicators="${indicators}preferred"
    fi

    echo "$indicators"
}

# Lists all refresh rates for given output and resolution
get_refreshrates() {
    rate_ln=$(get_modes "$1" | grep "\s$2\s") || exit 1

    if [[ -z "$rate_ln" ]]; then
        echo "Not a valid resolution for this output" >&2
        exit 1
    else
        rates=$(echo "${rate_ln// +/+/}" | tr -s " " | cut -d" " -f3- | sed 's/ /\n/g')
        for rate_s in $rates; do
            rate=${rate_s//[^0-9\.]*/}
            echo -n "$rate Hz"

            indicators=$(parse_indicators "$rate_s")

            if [[ -n $indicators ]]; then
                echo " ($indicators)"
            else
                echo ""
            fi
        done
    fi
}

# Passes options to rofi
# Arguments: Propmt, selection so far.
set_opts() {
    echo -en "\0prompt\x1f$1\n"
    echo -en "\0message\x1fSelected display: $2\n"
    echo -en "\0no-custom\x1ftrue\n"
    echo -en "\0keep-selection\x1ffalse\n"
}


# If called with no arguments, list outputs
if [[ $# == 0 ]]; then 
    echo -en "\0prompt\x1f \n"
    echo -en "\0no-custom\x1ftrue\n"

    get_outputs
fi

# If called with 1 argument, check ROFI_DATA
if [[ $# == 1 ]]; then 
    # If not yet set DATA, we are selecting a resolution
    if [[ -z ${ROFI_DATA} ]]; then
        echo -en "\0data\x1f$output\n"
        output="$(echo "$1" | xargs)" # strip whitespace
        res=$(get_resolutions "$output")

        set_opts " " "$1"

        if [[ -n $res ]]; then
            echo -e "Maximum available"
        fi
        echo -e "Turn off"
        echo -e "$res"

    # Otherwise, if only one data element, 
    # We are selecting a framerate for a resolution
    elif ! [[ $ROFI_DATA == *":"* ]]; then
        output=$ROFI_DATA
        resolution=$1

        if [[ "$resolution" == "Turn off" ]]; then
            coproc xrandr --output "$output" --off
            exit
        fi

        if [[ "$resolution" == "Maximum available" ]]; then
            resolution=$(get_resolutions "$output" | head -n 1)
        fi

        set_opts "龍" "$output ($resolution)"

        echo -en "\0data\x1f$output:$resolution\n"
        get_refreshrates "$output" "$resolution"

    # Othrwise, we have two data elements (output, resolution)
    # and an arg (refresh rate). Call xrandr wit these settings
    else
        opts=(${ROFI_DATA//:/ })
        output="${opts[0]}"
        resolution="${opts[1]}"
        framerate="${1//(.*)/}" # Remove indicators
        
        coproc xrandr --output "$output" --mode "$resolution" --rate "$framerate"
    fi
fi

# If called with 2 arguments (output,resolution), list refresh rates
if [[ $# == 2 ]]; then 
    echo -en "\0prompt\x1fSelect framerate for $1\n"
    get_refreshrates "$1" "$2"
fi

