#!/bin/bash

apply_resolution() {
    opts=(${ROFI_DATA//:/ })
    output="${opts[0]}"
    resolution="${opts[1]}"
    framerate="${1//(.*)/}" # Remove indicators

    coproc xrandr --output "$output" --mode "$resolution" --rate "$framerate"
}
