#!/bin/bash

source lib/get_modes
source lib/parse_ind

get_rates() {
    rate_ln=$(get_modes "$1" | grep "\s$2\s") || exit 1

    if [[ -z "$rate_ln" ]]; then
        echo "Not a valid resolution for this output" >&2
        exit 1
    else
        rates=$(echo "${rate_ln// +/+/}" | tr -s " " | cut -d" " -f3- | sed 's/ /\n/g')
        for rate_s in $rates; do
            rate=${rate_s//[^0-9\.]*/}
            echo -n "$rate Hz"

            indicators=$(parse_indicators "$rate_s")

            if [[ -n $indicators ]]; then
                echo " ($indicators)"
            else
                echo ""
            fi
        done
    fi
}

rofi_rates() {
    output=$ROFI_DATA
    resolution=$1

    if [[ "$resolution" == "Turn off" ]]; then
        coproc xrandr --output "$output" --off
        exit
    fi

    if [[ "$resolution" == "Maximum available" ]]; then
        resolution=$(get_resolutions "$@" | head -n 1)
    fi

    set_opts "龍" "$output ($resolution)"

    echo -en "\0data\x1f$output:$resolution\n"
    get_rates "$output" "$resolution"
}
