#!/bin/bash

get_modes() {
    res=$(xrandr | sed "1,/^$1\s/d" | sed "/^\w/Q")

    if [[ -z "$res" ]]; then 
        echo "No such X output" >&2
        exit 1
    else 
        echo "$res"
    fi
}

get_resolutions() { 
    get_modes "$1" | awk "{ print \$1 }" 
}

rofi_resolutions() {
    output="$(echo "$1" | xargs)" # strip whitespace
    res=$(get_resolutions "$output")

    set_opts " " "$output"

    # Add maximum option if more than 1 available
    if [[ $(echo $res | wc -l) > 1 ]]; then
        echo -e "Maximum available"
    fi
    echo -e "$res"
}

maximum_reolution() {
    get_resolutions "$@" | head -n 1
}
