#!/bin/bash

source $(dirname $0)/lib/get_modes
source $(dirname $0)/lib/parse_ind

get_maximum_rate() {
    get_rates "$@" | head -n 1
}

get_rates() {
    echo "getting rate ln for $1, on res $2" >&2
    rate_ln=$(get_modes "$1" | grep "\s$2\s") || exit 1

    if [[ -z "$rate_ln" ]]; then
        echo "Not a valid resolution for this output" >&2
        exit 1
    else
        rates=$(echo "${rate_ln// +/+/}" | tr -s " " | cut -d" " -f3- | sed 's/ /\n/g')
        for rate_s in $rates; do
            rate=${rate_s//[^0-9\.]*/}
            echo -n "$rate Hz"

            indicators=$(parse_indicators "$rate_s")

            if [[ -n $indicators ]]; then
                echo " ($indicators)"
            else
                echo ""
            fi
        done
    fi
}

rofi_rates() {
    output=$1
    resolution=$2

    if [[ "$resolution" == "Maximum available" ]]; then
        resolution=$(get_resolutions "$@" | head -n 1)
    fi

    set_opts "龍" "$output ($resolution)"
    echo "Maximum available"
    get_rates "$output" "$resolution"
}
