#!/bin/bash

parse_indicators() {
    indicators=""
    if [[ $1 == *"*"* ]]; then
        indicators="current"
    fi

    if [[ $1 == *"+"* ]]; then
        if [[ -n "$indicators" ]]; then
            indicators="${indicators}, "
        fi
        indicators="${indicators}preferred"
    fi

    echo "$indicators"
}

